
services:
  backend-service:
    build: ./backend
    ports:
      - "8000:8000"

  frontend-service:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html